#!/usr/bin/env python3
# sign-server.py
#
# Minimal HTTP service holding the lab's intermediate CA private key.
# Accepts a CSR, signs it, returns the resulting leaf certificate --
# but only for a hostname on an explicit allowlist, only if the CSR
# requests NO extensions of its own (extensions come only from this
# service's own LEAF_EXTENSIONS, never the client), and every request
# to every endpoint is logged regardless of outcome.
#
# Every subprocess.run call below uses list-form arguments (no shell
# involved at all), and the only variable components are file paths
# generated by this process itself inside a TemporaryDirectory --
# never raw CSR content or anything directly attacker-controlled.
# Flagged by ruff's S603 (subprocess with untrusted input) as a
# pattern worth double-checking; reviewed and confirmed safe on that
# basis, suppressed with justification rather than silently ignored.

import subprocess
import tempfile
import os
import json
from datetime import datetime, timezone
from flask import Flask, request, jsonify

app = Flask(__name__)

OPENSSL = "/usr/bin/openssl"
INTERMEDIATE_CERT = "/ca/intermediate-ca.crt"
INTERMEDIATE_KEY = "/ca/intermediate-ca.key"
AUDIT_LOG = "/ca/sign-audit.jsonl"
ACCESS_LOG = "/ca/access.jsonl"

ALLOWED_HOSTNAMES = {
    "web-target.internal",
    "linux-workstation-target.internal",
}

LEAF_EXTENSIONS = (
    "basicConstraints=critical,CA:FALSE\n"
    "keyUsage=critical,digitalSignature,keyEncipherment\n"
    "extendedKeyUsage=serverAuth\n"
)


def write_log(path, entry):
    with open(path, "a") as f:
        f.write(json.dumps(entry) + "\n")


def audit_log(hostname, outcome, detail=""):
    write_log(AUDIT_LOG, {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "requesting_ip": request.remote_addr,
        "requested_hostname": hostname,
        "outcome": outcome,
        "detail": detail,
    })


@app.after_request
def log_every_request(response):
    """Fires after EVERY request to EVERY endpoint, regardless of
    which route handled it or whether it succeeded -- a comprehensive
    access log, separate from /sign's own more detailed audit trail."""
    write_log(ACCESS_LOG, {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "requesting_ip": request.remote_addr,
        "method": request.method,
        "path": request.path,
        "status_code": response.status_code,
    })
    return response


def extract_csr_cn(csr_path):
    """Reads the Subject Common Name a CSR is actually requesting,
    BEFORE any signing happens -- this is what gets checked against
    ALLOWED_HOSTNAMES. Uses -nameopt RFC2253 for a predictable,
    tested output format: "subject=CN=web-target.internal", with no
    variable spacing to parse around."""
    result = subprocess.run(  # noqa: S603
        [
            OPENSSL, "req", "-in", csr_path,
            "-noout", "-subject", "-nameopt", "RFC2253",
        ],
        capture_output=True, text=True,
    )
    if result.returncode != 0 or "CN=" not in result.stdout:
        return None
    return result.stdout.split("CN=", 1)[1].strip()


def csr_requests_extensions(csr_path):
    """Checks whether the CSR itself is asking for ANY extensions at
    all -- CA:TRUE, keyUsage, SANs, anything. A CSR generated by this
    lab's own client-side script never requests extensions; the
    service alone decides them via LEAF_EXTENSIONS. Any CSR that DOES
    request something is treated as unexpected and rejected outright,
    not just silently overridden -- we want a record that this was
    attempted, not just proof the attempt didn't work."""
    result = subprocess.run(  # noqa: S603
        [OPENSSL, "req", "-in", csr_path, "-noout", "-text"],
        capture_output=True, text=True,
    )
    return "Requested Extensions" in result.stdout


@app.route("/sign", methods=["POST"])
def sign():
    csr_pem = request.get_data(as_text=True)

    if not csr_pem or "BEGIN CERTIFICATE REQUEST" not in csr_pem:
        audit_log(None, "rejected", "no valid CSR in request body")
        return jsonify({"error": "no valid CSR provided in request body"}), 400

    with tempfile.TemporaryDirectory() as tmpdir:
        csr_path = os.path.join(tmpdir, "request.csr")
        cert_path = os.path.join(tmpdir, "signed.crt")
        ext_path = os.path.join(tmpdir, "leaf.ext")

        with open(csr_path, "w") as f:
            f.write(csr_pem)

        requested_cn = extract_csr_cn(csr_path)

        if requested_cn not in ALLOWED_HOSTNAMES:
            audit_log(requested_cn, "rejected", "hostname not on allowlist")
            return jsonify({
                "error": f"hostname '{requested_cn}' is not authorized"
            }), 403

        if csr_requests_extensions(csr_path):
            audit_log(
                requested_cn, "rejected",
                "CSR requested its own extensions -- not permitted",
            )
            return jsonify({
                "error": "CSR must not request extensions; the CA decides them"
            }), 403

        with open(ext_path, "w") as f:
            f.write(LEAF_EXTENSIONS)

        result = subprocess.run(  # noqa: S603
            [
                OPENSSL, "x509", "-req",
                "-in", csr_path,
                "-CA", INTERMEDIATE_CERT,
                "-CAkey", INTERMEDIATE_KEY,
                "-CAcreateserial",
                "-out", cert_path,
                "-days", "90",
                "-extfile", ext_path,
            ],
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            audit_log(requested_cn, "failed", result.stderr[:500])
            return jsonify({"error": "signing failed", "detail": result.stderr}), 500

        with open(cert_path) as f:
            signed_cert = f.read()

    audit_log(requested_cn, "signed")
    return jsonify({"certificate": signed_cert})


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})


if __name__ == "__main__":
    # S104: intentional -- this service must be reachable by other
    # hosts on the internal network, not just from localhost. Same
    # justification as demo-controller/main.py's identical pattern.
    app.run(host="0.0.0.0", port=9443)  # noqa: S104
